--!strict

local SharedTypes = require(script.Parent.Parent.SharedTypes)
local EffectTypes = require(script.Parent.Parent.EffectTypes)

export type Source<T> = SharedTypes.Source<T>
export type Reactive<T> = SharedTypes.Reactive<T>
export type LiquidGradientOptions = EffectTypes.LiquidGradientOptions

export type ToggleSwitchProps = {
	name: string?,
	value: Source<boolean>,
	size: Reactive<UDim2>?,
	position: Reactive<UDim2>?,
	anchorPoint: Reactive<Vector2>?,
	visible: Reactive<boolean>?,
	layoutOrder: Reactive<number>?,
	zIndex: Reactive<number>?,
	disabled: Reactive<boolean>?,
	onChanged: ((boolean) -> ())?,
	backgroundColor3: Reactive<Color3>?,
	onBackgroundColor3: Reactive<Color3>?,
	fillColor3: Reactive<Color3>?,
	knobColor3: Reactive<Color3>?,
	onKnobColor3: Reactive<Color3>?,
	strokeColor3: Reactive<Color3>?,
	backgroundTransparency: Reactive<number>?,
	fillTransparency: Reactive<number>?,
	strokeTransparency: Reactive<number>?,
	strokeThickness: Reactive<number>?,
	cornerRadius: Reactive<UDim>?,
	knobSize: Reactive<UDim2>?,
	knobOffPosition: Reactive<UDim2>?,
	knobOnPosition: Reactive<UDim2>?,
	tweenDuration: number?,
}

export type ToggleButtonProps = {
	name: string?,
	value: Source<boolean>,
	size: Reactive<UDim2>?,
	position: Reactive<UDim2>?,
	anchorPoint: Reactive<Vector2>?,
	visible: Reactive<boolean>?,
	layoutOrder: Reactive<number>?,
	zIndex: Reactive<number>?,
	disabled: Reactive<boolean>?,
	onChanged: ((boolean) -> ())?,
	textOn: Reactive<string>?,
	textOff: Reactive<string>?,
	fontFace: Reactive<Font>?,
	textColor3: Reactive<Color3>?,
	onTextColor3: Reactive<Color3>?,
	backgroundColor3: Reactive<Color3>?,
	onBackgroundColor3: Reactive<Color3>?,
	backgroundTransparency: Reactive<number>?,
	gradient: Reactive<ColorSequence>?,
	onGradient: Reactive<ColorSequence>?,
	gradientRotation: Reactive<number>?,
	strokeColor3: Reactive<Color3>?,
	onStrokeColor3: Reactive<Color3>?,
	strokeTransparency: Reactive<number>?,
	strokeThickness: Reactive<number>?,
	cornerRadius: Reactive<UDim>?,
	aspectRatio: Reactive<number>?,
	minTextSize: Reactive<number>?,
	maxTextSize: Reactive<number>?,
}

export type SliderProps = {
	name: string?,
	value: Source<number>,
	min: number?,
	max: number?,
	step: number?,
	size: Reactive<UDim2>?,
	position: Reactive<UDim2>?,
	anchorPoint: Reactive<Vector2>?,
	visible: Reactive<boolean>?,
	layoutOrder: Reactive<number>?,
	zIndex: Reactive<number>?,
	disabled: Reactive<boolean>?,
	dimmed: Reactive<boolean>?,
	onChanged: ((number) -> ())?,
	backgroundColor3: Reactive<Color3>?,
	fillColor3: Reactive<Color3>?,
	fillGradient: Reactive<ColorSequence>?,
	fillGradientTransparency: Reactive<NumberSequence>?,
	fillGradientRotation: Reactive<number>?,
	fillGradientOffset: Reactive<Vector2>?,
	fillGradientEffect: LiquidGradientOptions?,
	knobColor3: Reactive<Color3>?,
	dimmedKnobColor3: Reactive<Color3>?,
	strokeColor3: Reactive<Color3>?,
	backgroundTransparency: Reactive<number>?,
	fillTransparency: Reactive<number>?,
	dimmedFillTransparency: Reactive<number>?,
	strokeTransparency: Reactive<number>?,
	strokeThickness: Reactive<number>?,
	cornerRadius: Reactive<UDim>?,
	knobSize: Reactive<UDim2>?,
}

return {}
